from __future__ import annotations

from datetime import datetime, timezone
import re
from typing import Any

from app.models.task import Task
from app.schemas.tasks import TaskSpec
from app.services.model_router import ModelRouter


class WorkerAgent:
    def __init__(self, model_router: ModelRouter | None = None) -> None:
        self.model_router = model_router

    def _slugify(self, text: str, fallback: str) -> str:
        normalized = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
        if not normalized:
            return fallback
        if normalized[0].isdigit():
            normalized = f"p_{normalized}"
        return normalized[:48]

    def _safe_text(self, value: Any, default: str = "") -> str:
        if isinstance(value, str):
            return value.strip()
        return default

    def _detect_scene(self, task: Task) -> str:
        constraints = task.constraints if isinstance(task.constraints, dict) else {}
        scene = self._safe_text(constraints.get("scenarioId"), "").lower()
        known = {
            "coding",
            "office",
            "research",
            "debug",
            "data",
            "product",
            "skills_factory",
            "video_creator",
        }
        if scene in known:
            return scene

        goal_text = task.goal.lower()
        if any(token in goal_text for token in ["skill", "skills", "prompt card"]):
            return "skills_factory"
        if any(token in goal_text for token in ["video", "storyboard", "script"]):
            return "video_creator"
        if any(token in goal_text for token in ["research", "analysis", "conclusion"]):
            return "research"
        if any(token in goal_text for token in ["debug", "error", "incident"]):
            return "debug"
        if any(token in goal_text for token in ["data", "sql", "dashboard", "metric"]):
            return "data"
        if any(token in goal_text for token in ["product", "prd", "roadmap", "feature spec"]):
            return "product"
        if any(token in goal_text for token in ["office", "brief", "summary", "report"]):
            return "office"
        return "coding"

    def _build_coding_files(self, task: Task, summary: str, llm_summary: str) -> list[dict[str, str]]:
        constraints = task.constraints if isinstance(task.constraints, dict) else {}
        language = self._safe_text(constraints.get("language"), "zh-CN")
        pkg = self._slugify(task.goal, fallback="beeagi_app")
        project_dir = f"{pkg}_{task.id[:8]}_project"
        context_block = "\n".join(f"- {ref}" for ref in (task.context_refs or [])) or "- (none)"
        summary_block = summary or task.goal
        llm_block = llm_summary or "No extra model notes."
        readme = (
            f"# {pkg}\n\n"
            "This runnable starter is generated by BeeAGI for the coding scenario.\n\n"
            "## Goal\n"
            f"{task.goal}\n\n"
            "## Context Refs\n"
            f"{context_block}\n\n"
            "## Quick Start\n"
            "```bash\n"
            "python -m venv .venv\n"
            ". .venv/Scripts/activate\n"
            "pip install -e .[dev]\n"
            f"python -m {pkg}.main\n"
            "pytest\n"
            "```\n\n"
            "## Acceptance Notes\n"
            f"- Language hint: {language}\n"
            f"- Quality target: {task.quality_target}\n"
            f"- Priority: {task.priority}\n\n"
            "## BeeAGI Execution Summary\n"
            f"{summary_block}\n\n"
            "## Model Notes\n"
            f"{llm_block}\n"
        )
        pyproject = (
            "[build-system]\n"
            "requires = [\"setuptools>=68\", \"wheel\"]\n"
            "build-backend = \"setuptools.build_meta\"\n\n"
            "[project]\n"
            f"name = \"{pkg}\"\n"
            "version = \"0.1.0\"\n"
            "description = \"Generated by BeeAGI coding delivery\"\n"
            "requires-python = \">=3.10\"\n\n"
            "[project.optional-dependencies]\n"
            "dev = [\"pytest>=8.0\"]\n\n"
            "[tool.pytest.ini_options]\n"
            "pythonpath = [\"src\"]\n"
            "testpaths = [\"tests\"]\n"
        )
        init_py = "__all__ = [\"build_task_plan\", \"render_deliverable\"]\n"
        planner_py = (
            "from __future__ import annotations\n\n"
            "from datetime import datetime, timezone\n"
            "from typing import Any\n\n\n"
            "def build_task_plan(goal: str, context_refs: list[str], constraints: dict[str, Any]) -> list[str]:\n"
            "    plan = [\n"
            "        \"Clarify acceptance criteria\",\n"
            "        \"Implement feature and guardrails\",\n"
            "        \"Run tests and document outcomes\",\n"
            "    ]\n"
            "    if context_refs:\n"
            "        plan.append(\"Cross-check with linked context refs\")\n"
            "    if constraints.get(\"doneWhen\"):\n"
            "        plan.append(\"Validate doneWhen checklist\")\n"
            "    return plan\n\n\n"
            "def render_deliverable(goal: str, plan: list[str], summary: str, llm_notes: str) -> str:\n"
            "    ts = datetime.now(timezone.utc).isoformat()\n"
            "    plan_block = \"\\\\n\".join(f\"- {item}\" for item in plan)\n"
            "    return (\n"
            "        f\"# Delivery Report\\n\\n\"\n"
            "        f\"Generated at: {ts}\\n\\n\"\n"
            "        f\"## Goal\\n{goal}\\n\\n\"\n"
            "        f\"## Execution Plan\\n{plan_block}\\n\\n\"\n"
            "        f\"## Execution Summary\\n{summary}\\n\\n\"\n"
            "        f\"## Model Notes\\n{llm_notes}\\n\"\n"
            "    )\n"
        )
        main_py = (
            "from __future__ import annotations\n\n"
            "from pathlib import Path\n\n"
            "from .planner import build_task_plan, render_deliverable\n\n\n"
            "def main() -> None:\n"
            f"    goal = {task.goal!r}\n"
            f"    context_refs = {list(task.context_refs or [])!r}\n"
            f"    constraints = {constraints!r}\n"
            f"    summary = {summary_block!r}\n"
            f"    llm_notes = {llm_block!r}\n\n"
            "    plan = build_task_plan(goal, context_refs, constraints)\n"
            "    report = render_deliverable(goal, plan, summary, llm_notes)\n"
            "    Path(\"deliverable.md\").write_text(report, encoding=\"utf-8\")\n"
            "    print(\"Deliverable written: deliverable.md\")\n\n\n"
            "if __name__ == \"__main__\":\n"
            "    main()\n"
        )
        test_py = (
            "from __future__ import annotations\n\n"
            f"from {pkg}.planner import build_task_plan\n\n\n"
            "def test_plan_contains_core_steps() -> None:\n"
            "    plan = build_task_plan(\"demo\", [\"repo://a\"], {\"doneWhen\": [\"tests\"]})\n"
            "    assert any(\"Implement feature\" in item for item in plan)\n"
            "    assert any(\"Validate doneWhen checklist\" in item for item in plan)\n"
        )
        return [
            {"path": f"{project_dir}/README.md", "kind": "doc", "description": "Project guide", "content": readme},
            {"path": f"{project_dir}/pyproject.toml", "kind": "code", "description": "Python project metadata", "content": pyproject},
            {"path": f"{project_dir}/src/{pkg}/__init__.py", "kind": "code", "description": "Package init", "content": init_py},
            {"path": f"{project_dir}/src/{pkg}/planner.py", "kind": "code", "description": "Planning and report rendering", "content": planner_py},
            {"path": f"{project_dir}/src/{pkg}/main.py", "kind": "code", "description": "Executable entrypoint", "content": main_py},
            {"path": f"{project_dir}/tests/test_planner.py", "kind": "code", "description": "Baseline test", "content": test_py},
        ]

    def _build_skill_files(self, task: Task, summary: str) -> list[dict[str, str]]:
        constraints = task.constraints if isinstance(task.constraints, dict) else {}
        hints = constraints.get("skillFactoryHints") if isinstance(constraints, dict) else {}
        hint_skill_id = ""
        if isinstance(hints, dict):
            hint_skill_id = self._safe_text(hints.get("targetSkillId"), "")
        skill_id = self._slugify(hint_skill_id or task.goal, fallback="skill_delivery")
        skill_dir = f"skills/{skill_id}"
        skill_md = (
            f"# Skill: {skill_id}\n\n"
            "## Purpose\n"
            f"{task.goal}\n\n"
            "## Input Schema\n"
            "```json\n"
            "{\n"
            "  \"goal\": \"string\",\n"
            "  \"contextRefs\": [\"string\"],\n"
            "  \"constraints\": {\"type\": \"object\"}\n"
            "}\n"
            "```\n\n"
            "## Output Schema\n"
            "```json\n"
            "{\n"
            "  \"summary\": \"string\",\n"
            "  \"artifacts\": [{\"path\": \"string\", \"description\": \"string\"}],\n"
            "  \"riskFlags\": [\"string\"]\n"
            "}\n"
            "```\n\n"
            "## Tool Boundaries\n"
            "- Filesystem: read/write inside bound workspace only\n"
            "- Network: optional and policy-gated\n"
            "- Evolution: guarded by shadow replay + canary + rollback\n\n"
            "## Acceptance\n"
            "- Output must include executable/usable artifacts\n"
            "- All changes must be auditable\n\n"
            "## Current Execution Summary\n"
            f"{summary or task.goal}\n"
        )
        examples_md = (
            "# Usage Example\n\n"
            "```markdown\n"
            "Goal: Build a reusable code review skill.\n"
            "Context: repo://backend, doc://quality-guidelines\n"
            "Constraints: {\"output\":\"SKILL.md\", \"risk\":\"low\"}\n"
            "```\n"
        )
        return [
            {"path": f"{skill_dir}/SKILL.md", "kind": "doc", "description": "Skill definition", "content": skill_md},
            {"path": f"{skill_dir}/EXAMPLES.md", "kind": "doc", "description": "Usage examples", "content": examples_md},
        ]

    def _build_markdown_delivery(
        self,
        *,
        scene: str,
        task: Task,
        summary: str,
        llm_summary: str,
        title: str,
        extra_sections: list[tuple[str, str]],
    ) -> list[dict[str, str]]:
        report_lines = [
            f"# {title}",
            "",
            "## Goal",
            task.goal,
            "",
            "## Execution Summary",
            summary or task.goal,
            "",
        ]
        if llm_summary:
            report_lines.extend(["## Model Notes", llm_summary, ""])
        for section_title, section_body in extra_sections:
            report_lines.extend([f"## {section_title}", section_body, ""])

        file_path = f"deliverables/{scene}/result.md"
        return [
            {
                "path": file_path,
                "kind": "doc",
                "description": f"{scene} report",
                "content": "\n".join(report_lines).strip() + "\n",
            }
        ]

    def build_deliverable_bundle(self, task: Task, execution_result: dict[str, Any]) -> dict[str, Any]:
        scene = self._detect_scene(task)
        summary = self._safe_text(execution_result.get("summary"), task.goal)
        llm_summary = self._safe_text(execution_result.get("llmSummary"), "")

        if scene == "coding":
            files = self._build_coding_files(task, summary, llm_summary)
            title = "Coding Project Delivery"
        elif scene == "skills_factory":
            files = self._build_skill_files(task, summary)
            title = "Skill Markdown Delivery"
        elif scene == "office":
            files = self._build_markdown_delivery(
                scene=scene,
                task=task,
                summary=summary,
                llm_summary=llm_summary,
                title="Office Delivery Brief",
                extra_sections=[
                    ("Action Items", "- Clarify owners\n- Set deadlines\n- Track weekly review"),
                    ("Risk Board", "- Dependency delay\n- Priority conflicts"),
                ],
            )
            title = "Office Delivery Brief"
        elif scene == "research":
            files = self._build_markdown_delivery(
                scene=scene,
                task=task,
                summary=summary,
                llm_summary=llm_summary,
                title="Research Analysis Report",
                extra_sections=[
                    ("Hypotheses", "- H1: behavior shift\n- H2: friction point"),
                    ("Evidence Checklist", "- Quantitative signals\n- Qualitative interviews"),
                ],
            )
            title = "Research Analysis Report"
        elif scene == "debug":
            files = self._build_markdown_delivery(
                scene=scene,
                task=task,
                summary=summary,
                llm_summary=llm_summary,
                title="Debug Incident Report",
                extra_sections=[
                    ("Reproduction", "1. Capture logs\n2. Isolate inputs\n3. Verify fix"),
                    ("Rollback Guard", "Define rollback trigger before deploy."),
                ],
            )
            title = "Debug Incident Report"
        elif scene == "data":
            sql = (
                "-- Example analysis skeleton generated by BeeAGI\n"
                "SELECT date_trunc('day', event_time) AS day, COUNT(*) AS events\n"
                "FROM events\n"
                "GROUP BY 1\n"
                "ORDER BY 1 DESC\n"
                "LIMIT 30;\n"
            )
            files = self._build_markdown_delivery(
                scene=scene,
                task=task,
                summary=summary,
                llm_summary=llm_summary,
                title="Data Workflow Report",
                extra_sections=[("Data SQL", "See companion file `analysis.sql`.")],
            ) + [
                {
                    "path": "deliverables/data/analysis.sql",
                    "kind": "code",
                    "description": "SQL starter",
                    "content": sql,
                }
            ]
            title = "Data Workflow Report"
        elif scene == "product":
            files = self._build_markdown_delivery(
                scene=scene,
                task=task,
                summary=summary,
                llm_summary=llm_summary,
                title="Product PRD",
                extra_sections=[
                    ("Milestones", "- Discovery\n- Build\n- Launch"),
                    ("Success Metrics", "- Activation\n- Retention\n- Error rate"),
                ],
            )
            title = "Product PRD"
        elif scene == "video_creator":
            storyboard = (
                "shot,seconds,visual,voiceover\n"
                "1,0-3,Hook scene,Open with pain point\n"
                "2,4-25,Product value,Show core capability\n"
                "3,26-50,Social proof,Highlight results\n"
                "4,51-60,CTA,Strong close and next action\n"
            )
            files = self._build_markdown_delivery(
                scene=scene,
                task=task,
                summary=summary,
                llm_summary=llm_summary,
                title="Short Video Script",
                extra_sections=[("Storyboard", "See companion file `storyboard.csv`.")],
            ) + [
                {
                    "path": "deliverables/video_creator/storyboard.csv",
                    "kind": "data",
                    "description": "Storyboard table",
                    "content": storyboard,
                }
            ]
            title = "Short Video Script"
        else:
            files = self._build_markdown_delivery(
                scene=scene,
                task=task,
                summary=summary,
                llm_summary=llm_summary,
                title="General Deliverable",
                extra_sections=[],
            )
            title = "General Deliverable"

        return {
            "scene": scene,
            "title": title,
            "files": files,
        }

    def _safe_int(self, value: Any, default: int, minimum: int, maximum: int) -> int:
        try:
            parsed = int(value)
        except (TypeError, ValueError):
            parsed = default
        return max(minimum, min(maximum, parsed))

    def _resolve_swarm_counts(self, constraints: dict[str, Any]) -> tuple[int, int]:
        swarm = constraints.get("swarmConfig") if isinstance(constraints, dict) else {}
        if not isinstance(swarm, dict):
            swarm = {}
        worker_count = self._safe_int(swarm.get("workerCount"), default=3, minimum=1, maximum=12)
        scout_count = self._safe_int(swarm.get("scoutCount"), default=2, minimum=1, maximum=12)
        return worker_count, scout_count

    def _collect_patch_effects(self, selected_skills: list[dict[str, Any]]) -> dict[str, Any]:
        patch_effects = {
            "promptTweaks": {},
            "toolPolicy": {},
            "sourceCandidates": [],
        }
        for runtime in selected_skills:
            if runtime.get("variant") != "canary":
                continue
            patch = runtime.get("candidatePatch")
            if not isinstance(patch, dict):
                continue
            prompt_tweaks = patch.get("promptTweaks")
            if isinstance(prompt_tweaks, dict):
                patch_effects["promptTweaks"].update(prompt_tweaks)
            tool_policy = patch.get("toolPolicy")
            if isinstance(tool_policy, dict):
                patch_effects["toolPolicy"].update(tool_policy)
            candidate_id = runtime.get("candidateId")
            if candidate_id:
                patch_effects["sourceCandidates"].append(candidate_id)
        return patch_effects

    def build_plan(self, spec: TaskSpec, scout_report: dict[str, Any]) -> dict[str, Any]:
        worker_count, scout_count = self._resolve_swarm_counts(spec.constraints)
        nodes = [{"id": "n1", "title": "Analyze intent", "owner": "worker-1"}]
        edges: list[dict[str, str]] = []

        previous = "n1"
        worker_node_ids: list[str] = []
        for idx in range(worker_count):
            node_id = f"w{idx + 1}"
            worker_node_ids.append(node_id)
            nodes.append(
                {
                    "id": node_id,
                    "title": f"Worker {idx + 1} parallel draft",
                    "owner": f"worker-{idx + 1}",
                }
            )
            edges.append({"from": previous, "to": node_id})

        ensemble_node = "ens1"
        nodes.append({"id": ensemble_node, "title": "Ensemble vote & recommendation", "owner": "worker-ensemble"})
        for worker_node in worker_node_ids:
            edges.append({"from": worker_node, "to": ensemble_node})

        execute_node = "n_exec"
        synth_node = "n_synth"
        nodes.extend(
            [
                {"id": execute_node, "title": "Execute toolchain", "owner": "worker-runtime"},
                {"id": synth_node, "title": "Synthesize output", "owner": "worker-runtime"},
            ]
        )
        edges.extend(
            [
                {"from": ensemble_node, "to": execute_node},
                {"from": execute_node, "to": synth_node},
            ]
        )

        risk_flags = list(scout_report.get("riskFlags", []))
        if worker_count >= 8:
            risk_flags.append("high_worker_parallelism_cost")
        return {
            "nodes": nodes,
            "edges": edges,
            "riskFlags": risk_flags,
            "swarmConfig": {"workerCount": worker_count, "scoutCount": scout_count},
        }

    def execute(
        self,
        task: Task,
        selected_skills: list[dict[str, Any]],
        scout_pheromones: list[dict[str, Any]] | None = None,
    ) -> tuple[dict[str, Any], dict[str, Any]]:
        started = datetime.now(timezone.utc)
        constraints = task.constraints if isinstance(task.constraints, dict) else {}
        worker_count, scout_count = self._resolve_swarm_counts(constraints)
        patch_effects = self._collect_patch_effects(selected_skills)
        prompt_tweaks = patch_effects.get("promptTweaks", {})
        tool_policy = patch_effects.get("toolPolicy", {})
        scout_pheromones = scout_pheromones or []

        max_retries = tool_policy.get("maxRetries") if isinstance(tool_policy, dict) else None
        prefer_low_risk = bool(tool_policy.get("preferLowRiskTools")) if isinstance(tool_policy, dict) else False
        format_hint = prompt_tweaks.get("format") if isinstance(prompt_tweaks, dict) else None
        style_hint = prompt_tweaks.get("style") if isinstance(prompt_tweaks, dict) else None

        prompt_suffix = ""
        if format_hint:
            prompt_suffix += f"\nOutput format hint: {format_hint}"
        if style_hint:
            prompt_suffix += f"\nStyle hint: {style_hint}"
        if isinstance(max_retries, int):
            prompt_suffix += f"\nTool retry budget override: {max_retries}"
        if prefer_low_risk:
            prompt_suffix += "\nPrefer low-risk tool paths when tradeoffs are close."

        prompt = (
            f"Task goal: {task.goal}\n"
            f"Constraints: {task.constraints}\n"
            f"Quality target: {task.quality_target}\n"
            f"Selected skills: {selected_skills}\n"
            f"Scout pheromones: {scout_pheromones}\n"
            "Generate a concise execution summary and key risks."
            f"{prompt_suffix}"
        )
        llm_output = None
        llm_meta: dict[str, Any] | None = None
        if self.model_router is not None:
            try:
                llm_result = self.model_router.generate(prompt)
                llm_output = llm_result.text
                llm_meta = {
                    "provider": llm_result.provider,
                    "model": llm_result.model,
                }
            except Exception as exc:  # pragma: no cover
                llm_output = f"LLM call failed: {exc}"
                llm_meta = {"provider": "error", "model": "n/a"}

        quality_estimate = min(0.98, max(0.6, task.quality_target - 0.02))
        if format_hint:
            quality_estimate = min(0.98, quality_estimate + 0.02)
        if prefer_low_risk:
            quality_estimate = min(0.98, quality_estimate + 0.01)

        result = {
            "summary": (
                f"Task '{task.goal}' executed with {len(selected_skills)} skills, "
                f"{worker_count} workers and {scout_count} scouts."
            ),
            "selectedSkills": selected_skills,
            "qualityEstimate": quality_estimate,
            "llmSummary": llm_output,
            "llmMeta": llm_meta,
            "swarmTelemetry": {
                "workerCount": worker_count,
                "scoutCount": scout_count,
                "ensembleMode": "weighted-vote",
                "ensembleRecommendation": "blend top 2 worker drafts then execute risk-aware path",
            },
            "appliedPatchSummary": {
                "promptTweaks": prompt_tweaks,
                "toolPolicy": tool_policy,
                "sourceCandidates": patch_effects["sourceCandidates"],
            },
            "scoutPheromones": scout_pheromones,
        }
        completed = datetime.now(timezone.utc)
        retry_count = 0
        if isinstance(max_retries, int):
            retry_count = max(0, min(max_retries, 5))

        error_rate = 0.0
        if prefer_low_risk:
            error_rate = 0.0
        elif isinstance(max_retries, int) and max_retries <= 1:
            error_rate = 0.01

        prompt_tokens = max(24, len(prompt) // 4)
        completion_source = llm_output or result["summary"]
        completion_tokens = max(24, len(str(completion_source)) // 4)
        total_tokens = prompt_tokens + completion_tokens

        metrics = {
            "durationMs": int((completed - started).total_seconds() * 1000) + 120,
            "retryCount": retry_count,
            "tokenEstimate": total_tokens,
            "promptTokens": prompt_tokens,
            "completionTokens": completion_tokens,
            "totalTokens": total_tokens,
            "errorRate": error_rate,
            "workerCount": worker_count,
            "scoutCount": scout_count,
        }
        return result, metrics
